name: PlainBase
description: $description
version: '${version}'

main: de.jgaertig.plainBase.PlainBase
bootstrapper: de.jgaertig.plainBase.PlainBaseBootstrap
loader: de.jgaertig.plainBase.PlainBaseLoader
api-version: '26.1.2'
load: POSTWORLD

authors: [ j-gaertig ]
website: https://github.com/j-gaertig/